language: c

before_install:
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-devel mono-gmcs > /dev/null
  - mozroots --import --sync

env:
  - EnableNuGetPackageRestore=true

script:
  - xbuild src/Muto\ Mark.sln